Use "module" in addition to "jsnext:main"
This change (probably) fixes my cryptic error

```
Error: 'default' is not exported by node_modules\rollup-plugin-alias\dist\rollup-plugin-alias.js
```

which I assume means it is loading `rollup-plugin-alias\dist\rollup-plugin-alias.js` instead of `rollup-plugin-alias\dist\rollup-plugin-alias.es2015js`, which I assume is because `rollup-plugin-node-resolve` uses the default options `module: true, main: true, jsnext: false`.

I think this PR is very minimal and will not have any adverse effects or break compatibility, but you never know.